import { ClipboardList, Grid2X2, LayoutDashboard, LogOut, Menu, Package, UtensilsCrossed, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link, NavLink, Outlet, useNavigate } from 'react-router-dom'
import { LoadingPanel } from '../components/StatePanel'
import { api, ensureCsrf } from '../lib/api'

export function AdminLayout() {
  const [checking, setChecking] = useState(true); const [open, setOpen] = useState(false); const navigate = useNavigate()
  useEffect(() => { api.get<{ authenticated: boolean }>('/admin/auth/session').then(response => { if (!response.data.authenticated) navigate('/admin/login', { replace: true }) }).catch(() => navigate('/admin/login', { replace: true })).finally(() => setChecking(false)) }, [navigate])
  const logout = async () => { await ensureCsrf(); await api.post('/admin/auth/logout'); navigate('/admin/login', { replace: true }) }
  const links = [{ to: '/admin', label: 'Overview', icon: LayoutDashboard, end: true }, { to: '/admin/orders', label: 'Orders', icon: ClipboardList }, { to: '/admin/products', label: 'Products', icon: Package }, { to: '/admin/categories', label: 'Categories', icon: Grid2X2 }]
  if (checking) return <div className="min-h-screen bg-slate-50"><LoadingPanel label="Opening the dashboard..." /></div>
  return <div className="min-h-screen bg-slate-50 text-slate-900"><aside className={`fixed inset-y-0 left-0 z-50 w-72 bg-forest-900 p-5 text-white transition-transform lg:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}><div className="flex h-14 items-center justify-between"><Link to="/admin" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-orange-500"><UtensilsCrossed size={20} /></span><span><b className="block font-display text-lg">Plate & Pantry</b><small className="text-white/50">Kitchen console</small></span></Link><button className="lg:hidden" onClick={() => setOpen(false)}><X /></button></div><nav className="mt-9 space-y-2">{links.map(({ to, label, icon: Icon, end }) => <NavLink end={end} key={to} to={to} onClick={() => setOpen(false)} className={({ isActive }) => `flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-bold transition ${isActive ? 'bg-white text-forest-900' : 'text-white/65 hover:bg-white/10 hover:text-white'}`}><Icon size={18} />{label}</NavLink>)}</nav><div className="absolute bottom-5 left-5 right-5 space-y-2"><Link to="/" className="flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-bold text-white/60 hover:bg-white/10">View storefront</Link><button onClick={() => void logout()} className="flex w-full items-center gap-3 rounded-xl px-4 py-3 text-sm font-bold text-white/60 hover:bg-white/10"><LogOut size={18} /> Sign out</button></div></aside>{open && <button className="fixed inset-0 z-40 bg-black/35 lg:hidden" aria-label="Close navigation" onClick={() => setOpen(false)} />}<div className="lg:pl-72"><header className="sticky top-0 z-30 flex h-18 items-center justify-between border-b border-slate-200 bg-white/95 px-5 backdrop-blur sm:px-8"><button className="lg:hidden" onClick={() => setOpen(true)}><Menu /></button><div className="ml-auto text-right"><p className="text-sm font-bold">Kitchen operations</p><p className="text-xs text-slate-400">Sri Lanka time</p></div></header><main className="p-5 sm:p-8"><Outlet /></main></div></div>
}
