import { LockKeyhole, UtensilsCrossed } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import { api, ensureCsrf, errorMessage } from '../lib/api'

export function AdminLoginPage() {
  const navigate = useNavigate(); const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { api.get<{ authenticated: boolean }>('/admin/auth/session').then(response => { if (response.data.authenticated) navigate('/admin', { replace: true }) }).catch(() => undefined) }, [navigate])
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await ensureCsrf(); await api.post('/admin/auth/login', { username, password }); navigate('/admin', { replace: true }) } catch (reason) { setError(errorMessage(reason, 'Sign in failed.')) } finally { setBusy(false) } }
  return <main className="grid min-h-screen bg-cream-50 lg:grid-cols-2"><section className="hidden bg-forest-900 p-12 text-white lg:flex lg:flex-col lg:justify-between"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-orange-500"><UtensilsCrossed /></span><b className="font-display text-xl">Plate & Pantry</b></div><div><p className="eyebrow">Kitchen console</p><h1 className="mt-4 max-w-lg font-display text-5xl leading-tight">Keep every plate, payment and delivery moving.</h1><p className="mt-5 max-w-md leading-7 text-white/55">Secure access for restaurant administrators only. Customer accounts are intentionally not required.</p></div><p className="text-xs text-white/35">Protected by server sessions, BCrypt and CSRF validation.</p></section><section className="flex items-center justify-center p-6"><form onSubmit={submit} className="w-full max-w-md rounded-3xl bg-white p-7 shadow-xl sm:p-10"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-orange-100 text-orange-600"><LockKeyhole /></span><h1 className="mt-6 font-display text-3xl font-bold">Welcome back</h1><p className="mt-2 text-sm leading-6 text-forest-900/50">Sign in with the administrator credentials configured on the server.</p>{error && <div className="mt-5 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>}<label className="mt-7 block"><span className="label">Username</span><input className="field" required autoComplete="username" value={username} onChange={e => setUsername(e.target.value)} /></label><label className="mt-5 block"><span className="label">Password</span><input className="field" type="password" required autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} /></label><button className="btn-primary mt-7 w-full" disabled={busy}>{busy ? 'Signing in...' : 'Sign in securely'}</button></form></section></main>
}
