import { Edit3, Plus, X } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { ErrorPanel, LoadingPanel } from '../components/StatePanel'
import { api, ensureCsrf, errorMessage } from '../lib/api'
import type { Category } from '../types'

type CategoryForm = { name: string; slug: string; sortOrder: number; active: boolean }
export function CategoriesPage() {
  const [categories, setCategories] = useState<Category[]>([]); const [editing, setEditing] = useState<Category | null | undefined>(undefined); const [form, setForm] = useState<CategoryForm>({ name: '', slug: '', sortOrder: 0, active: true }); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = () => api.get<Category[]>('/admin/categories').then(response => { setCategories(response.data); setError('') }).catch(reason => setError(errorMessage(reason))).finally(() => setLoading(false))
  useEffect(() => { void load() }, [])
  const open = (category: Category | null) => { setEditing(category); setForm(category ? { name: category.name, slug: category.slug, sortOrder: category.sortOrder, active: category.active } : { name: '', slug: '', sortOrder: categories.length + 1, active: true }); setError('') }
  const save = async (event: FormEvent) => { event.preventDefault(); try { await ensureCsrf(); editing ? await api.put(`/admin/categories/${editing.id}`, form) : await api.post('/admin/categories', form); setEditing(undefined); await load() } catch (reason) { setError(errorMessage(reason)) } }
  return <><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-bold text-orange-600">Menu structure</p><h1 className="mt-1 font-display text-3xl font-bold">Categories</h1><p className="mt-2 text-sm text-slate-500">Organise how customers browse the menu.</p></div><button className="btn-primary" onClick={() => open(null)}><Plus size={18} /> Add category</button></div>{loading ? <LoadingPanel /> : error && editing === undefined ? <div className="mt-8"><ErrorPanel message={error} retry={load} /></div> : <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{categories.map(category => <article className="admin-card" key={category.id}><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-orange-100 font-bold text-orange-700">{category.sortOrder}</span><button className="rounded-lg border border-slate-200 p-2" onClick={() => open(category)}><Edit3 size={16} /></button></div><h2 className="mt-5 font-display text-xl font-bold">{category.name}</h2><p className="mt-1 text-sm text-slate-400">/{category.slug}</p><span className={`mt-4 inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${category.active ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-600'}`}>{category.active ? 'Visible' : 'Hidden'}</span></article>)}</div>}{editing !== undefined && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4"><form onSubmit={save} className="w-full max-w-lg rounded-3xl bg-white p-7 shadow-2xl"><div className="flex justify-between"><h2 className="font-display text-2xl font-bold">{editing ? 'Edit category' : 'New category'}</h2><button type="button" onClick={() => setEditing(undefined)}><X /></button></div>{error && <div className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>}<label className="mt-6 block"><span className="label">Name</span><input className="field" required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label className="mt-4 block"><span className="label">Slug</span><input className="field" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={form.slug} onChange={e => setForm({ ...form, slug: e.target.value })} /></label><label className="mt-4 block"><span className="label">Sort order</span><input className="field" required type="number" min="0" value={form.sortOrder} onChange={e => setForm({ ...form, sortOrder: Number(e.target.value) })} /></label><label className="mt-5 flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={form.active} onChange={e => setForm({ ...form, active: e.target.checked })} /> Visible to customers</label><button className="btn-primary mt-7 w-full">Save category</button></form></div>}</>
}
