import { ArrowRight, Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { EmptyPanel } from '../components/StatePanel'
import { useCart } from '../context/CartContext'
import { money } from '../lib/api'

export function CartPage() {
  const { lines, subtotal, setQuantity, remove } = useCart(); const delivery = lines.length ? 350 : 0
  return <section className="container-shell py-12 sm:py-16"><p className="eyebrow">Your order</p><h1 className="display-title mt-4">The basket</h1>{lines.length === 0 ? <div className="mt-10"><EmptyPanel title="Your basket is waiting" body="Add a comforting plate, a cool drink, or something sweet from the menu." /><div className="mt-6 text-center"><Link to="/menu" className="btn-primary">Browse the menu</Link></div></div> : <div className="mt-10 grid gap-8 lg:grid-cols-[1fr_380px]"><div className="space-y-4">{lines.map(line => <article key={line.product.id} className="card flex gap-4 p-4 sm:gap-6"><img src={line.product.imageUrl} className="h-24 w-24 rounded-2xl object-cover sm:h-32 sm:w-32" alt="" /><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-orange-600">{line.product.category.name}</p><h2 className="mt-1 font-display text-xl font-bold">{line.product.name}</h2></div><button className="text-forest-900/35 hover:text-red-600" onClick={() => remove(line.product.id)} aria-label={`Remove ${line.product.name}`}><Trash2 size={18} /></button></div><div className="mt-5 flex items-end justify-between"><div className="flex items-center rounded-full border border-forest-900/10 p-1"><button className="grid h-8 w-8 place-items-center rounded-full hover:bg-cream-100" onClick={() => setQuantity(line.product.id, line.quantity - 1)}><Minus size={14} /></button><span className="w-8 text-center text-sm font-bold">{line.quantity}</span><button className="grid h-8 w-8 place-items-center rounded-full hover:bg-cream-100" onClick={() => setQuantity(line.product.id, line.quantity + 1)}><Plus size={14} /></button></div><span className="font-bold">{money(line.product.price * line.quantity)}</span></div></div></article>)}</div><aside className="card h-fit p-6 lg:sticky lg:top-28"><div className="flex items-center gap-3"><ShoppingBag className="text-orange-500" /><h2 className="font-display text-2xl font-bold">Order summary</h2></div><dl className="mt-7 space-y-4 text-sm"><div className="flex justify-between text-forest-900/60"><dt>Subtotal</dt><dd>{money(subtotal)}</dd></div><div className="flex justify-between text-forest-900/60"><dt>Delivery</dt><dd>{money(delivery)}</dd></div><div className="flex justify-between border-t border-forest-900/10 pt-4 text-lg font-bold"><dt>Total</dt><dd>{money(subtotal + delivery)}</dd></div></dl><Link to="/checkout" className="btn-primary mt-7 w-full">Continue to checkout <ArrowRight size={17} /></Link><Link to="/menu" className="mt-3 block text-center text-sm font-bold text-forest-900/50 hover:text-orange-600">Add more dishes</Link></aside></div>}</section>
}
